### ISSUE TITLE
Tentar manter a estrutura base

### ISSUE THREAD

**Issue by lucasferreira** [Cocalense/atendimento-chat#4]
Opa,

Cara a minha primeira dica é tentar manter a estrutura básica:

https://github.com/Cocalense/atv-sw-chat/blob/90036626aadd6a6fb0315e6143e4fff3432d4171/novoChat/chat.html#L16-L27

Perceba o código do `.tituloLeft`:

```html
<div class="tituloLeft"> 
     <p>Atendente diz:</p>  
         <div class="boxTextLeft"> 
             <p class="texto">mensagem do atendente </p> 
         </div> 
 </div> 
```

Agora olha o código do restante:

```html
<div class="tituloRight"> 
     <p>Você diz : </p> 
 </div> 
 <div class="boxTextRight"> 
     <p class="texto">mensagem do usuario </p>     
 </div>
```

O `.tituloLeft` estava seguindo um conceito de component, perceba que tu tinhas uma div "maior" que encapsulava toda a mensagem. Já no `.tituloLeft` e `.boxTextRight` tu deixou tudo solto, não recomendo fica mais difícil de replicar e controlar.

Eu faria o `.tituloRight` acima como o "left":

```html
<div class="tituloRight"> 
  <p>Você diz:</p> 
  <div class="boxTextRight"> 
     <p class="texto">mensagem do usuario</p>     
  </div>
</div> 
```

Ou seja, mantemos o `div.tituloRight` como "div maior" como container, e dentro dele os outros components necessários para termos uma "nova mensagem" Depois iremos usar isso como base no JavaScript, beleza?

**Comment by Cocalense** [comment]
de fato, fui fazendo alterações e devo ter esquecido desta parte!
